$(".bottom_button").click(function(){
			alert("Yo!!!");
		});
		$(".bottom_button").mouseover(function(){
			$(this).css("color","red");
		});
		$(".bottom_button").mouseout(function(){
			$(".bottom_button").css("color","white");
		});